name: admin-app-prod

services:
  app:
    container_name: admin-app
    image: admin-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - TZ=Asia/Yekaterinburg
      - NODE_ENV=production
    env_file:
      - ./.env
    ports:
      - 3006:3000
    restart: unless-stopped
