export { useClientProjectsApi } from './api/client-projects-api'
export { getClientProjectsQueryKey, getClientProjectsDetailQueryKey } from './api/query-keys'
export { default as ClientProjectsDetailInfo } from './ui/ClientProjectsDetailInfo.vue'
export { default as ClientProjectsDetailFiles } from './ui/ClientProjectsDetailFiles.vue'
export { default as ClientProjectsDetailComments } from './ui/ClientProjectsDetailComments.vue'
export { default as ClientProjectsDetailState } from './ui/ClientProjectsDetailState.vue'
